### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by paul7683** [fizzywhizbang/unrarall#1]
I need a hacker ottogoinsotto@gmail.com

**Comment by fizzywhizbang** [comment]
what do you need more specifically

**Comment by paul7683** [comment]
I am in need of a hacker.

**Comment by paul7683** [comment]
If you know anyone please send them my info ..My child and i have lost
everything someone burned our house down and we lost every thing I am sure
i know who it is but need to prove it .. there is so much more to this
story This person need to pay the price its my childs mother and if you can
help pleas get with me
